package com.example.retrofitapp;

import com.google.gson.annotations.SerializedName;

public class Post {
    private int userId;
    private Integer id;
    private String title;

    @SerializedName("body") //notify that text is body in GSON annotation
    private String text;

    public Post(int userId, String title, String text) { //the id will be generated by REST API
        this.userId = userId;
        this.title = title;
        this.text = text;
    }
    public int getUserId() {
        return userId;
    }

    public Integer getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getText() {
        return text;
    }
}
